version: "3"

services:
  nuxt-app:
    container_name: nuxt-app
    image: asciix12/nuxt-app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"